### ISSUE TITLE
这个肯定不能爬版权歌曲吧？

### ISSUE THREAD

**Issue by lirener** [qiangzi7723/spider-for-netease-music#1]
这个肯定不能爬版权歌曲吧？除非写了会员登录的cookies？
写完按照分类来拼凑歌单似乎也不错？

**Comment by qiangzi7723** [comment]
@lirener 只是抓取评论，不是下载这首歌曲，所以理论上只要歌曲在网易云上都可以抓取到，即使是版权歌曲在不登录的状态下也是可以获取到评论相关的数据。

**Comment by wangDelegate** [comment]
怎么不用Python 来爬呢?

**Comment by qiangzi7723** [comment]
因为是前端，所以就写了Node版本
