### ISSUE TITLE
只能爬取歌手？

### ISSUE THREAD

**Issue by tomdogandcat** [qiangzi7723/spider-for-netease-music#2]
运行显示歌手xxx抓取完毕，但是数据表却看不到歌曲的信息

**Comment by qiangzi7723** [comment]
@tomdogandcat 文档上说了啊。`node singer.js`这份代码是爬取歌手信息，先有了歌手信息才能爬歌曲信息。等歌手爬完存到数据库后再运行`node song.js`就可以爬取歌曲信息了。

**Comment by tomdogandcat** [comment]
歌手已经爬完了，在爬歌曲，命令行那里显示已抓取，但是数据库，歌曲表却是空的


在 2017年8月22日，下午3:40，qiangzi7723 <notifications@github.com<mailto:notifications@github.com>> 写道：


@tomdogandcat<https://github.com/tomdogandcat> 文档上说了啊。node singer.js这份代码是爬取歌手信息，先有了歌手信息才能爬歌曲信息。等歌手爬完存到数据库后再运行node song.js就可以爬取歌曲信息了。

**Comment by qiangzi7723** [comment]
问题解决了吗？数据库有没有连接正常？创表了吗？

**Comment by tomdogandcat** [comment]
是的


发自我的 iPhone

在 2017年8月27日，上午4:30，qiangzi7723 <notifications@github.com<mailto:notifications@github.com>> 写道：


Closed #2<https://github.com/qiangzi7723/spider-for-netease-music/issues/2>.
