### ISSUE TITLE
请求移除不必要的依赖（nightmare）

### ISSUE THREAD

**Issue by ianchn** [qiangzi7723/spider-for-netease-music#3]
网易云的页面由 前端 JS 控制路由动态加载，但可以找到页面源地址。

如 https://music.163.com/#/discover/artist/cat?id=1001&initial=65
源地址为 https://music.163.com/discover/artist/cat?id=1001&initial=65

直接请求源地址而不用无头浏览器可以提高爬取效率。希望之后的版本能改进。

**Comment by qiangzi7723** [comment]
嗯嗯，等下我更新一个新的版本，把nightmare移除掉。

**Comment by qiangzi7723** [comment]
已经更新了，去除了nightmare。速度还没有测试，理论上会比原来的版本还要再快
